#!/usr/bin/env bash

# Tarkista, että skripti ajetaan sudo:lla
if [ "$EUID" -ne 0 ]; then
    echo "Tämä skripti on suoritettava sudo:lla." >&2
    exit 1
fi

cp /usr/share/X11/xkb/symbols/fi /usr/share/X11/xkb/symbols/fi.bak
cp ./fi_custom /usr/share/X11/xkb/symbols/fi

# Aseta konsoleille
localectl set-keymap fi
# Aseta X11-ympäristölle
localectl set-x11-keymap fi

# Tarkista, että layout vaihto on onnistunut
localectl status

echo "Keyboard files copied successfully"
