#!/usr/bin/env bash

gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 9

gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'
gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'flat'

gsettings set org.gnome.desktop.interface text-scaling-factor 1.7
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.search-providers disable-external true
