#!/usr/bin/env bash

gsettings list-recursively org.gnome.desktop.wm.keybindings ;
gsettings list-recursively org.gnome.settings-daemon.plugins.media-keys ;
gsettings list-recursively org.gnome.settings-daemon.plugins.power ;
gsettings list-recursively org.gnome.shell.keybindings
